# Arctic regions geospatial wrangling

In [7]:
import pandas as pd
import geopandas as gpd
import os

In [8]:
os.environ['PROJ_LIB'] = '/opt/anaconda3/share/proj'

In [9]:
df = gpd.read_file('data/arctic_communities.geojson')

In [10]:
df.head()

,admin,country,n_communities,geometry
0,United States of America,US,115,"MULTIPOLYGON (((-132.74687 56.52568, -132.7576..."
1,United Kingdom,GB,96,"MULTIPOLYGON (((-2.66768 51.62300, -2.74214 51..."
2,Sweden,SE,133,"MULTIPOLYGON (((19.07646 57.83594, 18.99375 57..."
3,Russia,RU,774,"MULTIPOLYGON (((145.88154 43.45952, 145.89561 ..."
4,Norway,NO,48,"MULTIPOLYGON (((20.62217 69.03687, 20.49199 69..."

In [11]:
df.geom_type

0     MultiPolygon
1     MultiPolygon
2     MultiPolygon
3     MultiPolygon
4     MultiPolygon
5     MultiPolygon
6          Polygon
7          Polygon
8     MultiPolygon
9     MultiPolygon
10    MultiPolygon
11    MultiPolygon
12    MultiPolygon
13    MultiPolygon
14         Polygon
dtype: object

`df.geom_type` tells us all the geometry of all the variables.

In [12]:
df.geom_type.unique()

array(['MultiPolygon', 'Polygon'], dtype=object)

In [14]:
# Make an if/else statemnt to check geometries
if len(df.geom_type.unique()) != 1:
    print(f"Multiple feature types: {df.geom_type.unique()}")
else:
    print(f"All feature are:{df.geom_type.unique()}")

Multiple feature types: ['MultiPolygon' 'Polygon']

In [22]:
# Make an if else statement function 
def check_polygons(df1):
    if len(df1.geom_type.unique()) != 1:
        print(f"Multiple feature types: {df.geom_type.unique()}")
    else:
        print(f"All feature are:{df.geom_type.unique()}")

In [16]:
check_polygons(df)

Multiple feature types: ['MultiPolygon' 'Polygon']

## Explode polygons

In [19]:
df = df.explode(column = 'geometry', index_parts = False).reset_index()

In [20]:
df

,index,admin,country,n_communities,geometry
0,0,United States of America,US,115,"POLYGON ((-132.74687 56.52568, -132.75762 56.5..."
1,0,United States of America,US,115,"POLYGON ((-132.77988 56.24727, -132.83096 56.2..."
2,0,United States of America,US,115,"POLYGON ((-134.31274 58.22891, -134.31987 58.2..."
3,0,United States of America,US,115,"POLYGON ((-145.11851 60.33711, -145.15049 60.3..."
4,0,United States of America,US,115,"POLYGON ((-144.56563 59.81841, -144.61357 59.8..."
...,...,...,...,...,...
476,13,Canada,CA,7,"POLYGON ((-109.16641 67.98237, -109.05391 67.9..."
477,13,Canada,CA,7,"POLYGON ((-108.09272 67.00518, -107.96646 66.9..."
478,13,Canada,CA,7,"POLYGON ((-109.32314 67.99087, -109.36084 67.9..."
479,13,Canada,CA,7,"POLYGON ((-139.04312 69.57690, -139.12573 69.5..."
480,14,Belarus,BY,8,"POLYGON ((31.76338 52.10107, 31.57373 52.10811..."

In [23]:
check_polygons(df)

All feature are:['Polygon']